groups/urls.py
from django.urls import path

from groups.views import GroupCreateView, GroupDeleteView, GroupListView,  GroupUpdateView

app_name = 'groups'

urlpatterns = [
    path('', GroupListView.as_view(), name='list'),
    path('create/', GroupCreateView.as_view(), name='create'),
    path('update/<int:pk>/', GroupUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', GroupDeleteView.as_view(), name='delete'),
]

lms/urls.py
from core.views import index

import debug_toolbar

from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('groups/', include('groups.urls')),
    path('teachers/', include('teachers.urls')),
    path('courses/', include('courses.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

groups/models.py
import datetime

from core.models import Person

from django.db import models

from faker import Faker

from groups.validators import adult_validation

from teachers.models import Teacher


class Group(Person):
    phone_number = models.CharField(max_length=70, unique=True, blank=True, null=True)
    birthday = models.DateField(default=datetime.date.today, validators=[adult_validation])
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, null=True, related_name='students')

    def __str__(self):
        return f' {self.phone_number}, {self.birthday}, {self.teacher}, {self.first_name}, {self.last_name}'

    @staticmethod
    def generate_groups(count):
        faker = Faker()
        for _ in range(count):
            st = Group(
                first_name=faker.first_name(),
                last_name=faker.last_name(),
                city=faker.city(),
                phone_number=faker.phone_number(),
                email=faker.email(),
            )
            st.save()

groups/forms.py
from django.core.exceptions import ValidationError
from django.forms import DateInput, ModelForm

import django_filters # noqa

from groups.models import Group


class GroupBaseForm(ModelForm):
    class Meta:
        model = Group
        fields = ['first_name', 'last_name', 'city', 'phone_number', 'birthday', 'email']
        widgets = {
            'birthday': DateInput(attrs={'type': 'date'})
            }

    @staticmethod
    def normalize_name(value):
        return value.lower().capitalize()

    @staticmethod
    def normalize_phone_number(value):
        return ''.join(c for c in value if c.isdigit() or c == '+')

    def clean_first_name(self):
        first_name = self.cleaned_data['first_name']
        result = self.normalize_name(first_name)
        return result

    def clean_last_name(self):
        last_name = self.cleaned_data['last_name']
        result = self.normalize_name(last_name)
        return result

    def clean_phone_number(self):
        phone_number = self.cleaned_data['phone_number']
        if Group.objects.filter(phone_number=phone_number).exclude(id=self.instance.id).exists():
            raise ValidationError("Already exist")
        result = self.normalize_phone_number(phone_number)
        return result


class GroupCreateForm(GroupBaseForm):
    pass


class GroupUpdateForm(GroupBaseForm):
    pass


class GroupDeleteForm(GroupBaseForm):
    pass

class GroupsFilter(django_filters.FilterSet):
    class Meta:
        model = Group
        fields = {
            'first_name': ['exact', 'icontains'],
            'last_name': ['exact', 'startswith'],
        }

groups/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect # noqa
from django.shortcuts import get_object_or_404, render # noqa
from django.urls import reverse, reverse_lazy # noqa
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from faker import Faker # noqa

from groups.forms import GroupBaseForm, GroupCreateForm, GroupDeleteForm, GroupUpdateForm, GroupsFilter
from groups.models import Group


from webargs import fields # noqa
from webargs.djangoparser import use_args, use_kwargs # noqa

from copy import copy
# fake = Faker()
#
#
# @use_kwargs({
#     "count": fields.Int(
#         required=False,
#         missing=10
#      )},
#     location="query"
#     )
# def generate_students(request, count):
#     fake = Faker()
#     fake_n = []
#     for i in range(count):
#         fake_n.append(str(fake.name()).split())
#         fake_n.append(fake.phone_number())
#     s = Group(first_name=fake_n[0][0], last_name=fake_n[0][1], phone_number=fake_n[1])
#     s.save()
#     return HttpResponse(fake_n)


# @use_args({
#     "first_name": fields.Str(
#         required=False
#         ),
#     "last_name": fields.Str(
#         required=False
#         ),
#     "city": fields.Str(
#         required=False
#         ),
#     "birthday": fields.Str(
#         required=False
#         ),
#     "phone_number": fields.Str(
#         required=False
#         ),
#     "email": fields.Str(
#         required=False
#         )},
#     location="query"
#         )


class GroupListView(LoginRequiredMixin, ListView):
    paginate_by = 15
    model = Group
    form_class = GroupBaseForm
    success_url = reverse_lazy('groups:list')
    template_name = 'groups/list.html'

    def get_filter(self):
        return GroupsFilter(
            data=self.request.GET,
            queryset=self.model.objects.all().select_related('number_course').order_by('id')
        )

    def get_queryset(self):
        return self.get_filter().qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_filter'] = self.get_filter()
        return context


# def get_groups(request):
#     groups = Group.objects.all().select_related('teacher')
#     # for param_name, param_values in args.items():
#     #     if param_values:
#     #         groups = groups.filter(**{param_name: param_values})
#
#     obj_filter = GroupsFilter(data=request.GET, queryset=groups)
#
#     return render(
#         request=request,
#         template_name='groups/list.html',
#         context={
#             #'groups': groups,
#             'obj_filter': obj_filter,
#         }
#     )


class GroupCreateView(LoginRequiredMixin, CreateView):
    model = Group
    form_class = GroupCreateForm
    success_url = reverse_lazy('groups:list')
    template_name = 'groups/create.html'

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, 'A new student successfully added')

        return result

# def create_group(request):
#
#     if request.method == 'GET':
#
#         form = GroupCreateForm()
#
#     elif request.method == 'POST':
#
#         form = GroupCreateForm(request.POST)
#
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('groups:list'))
#
#     return render(
#         request=request,
#         template_name='groups/create.html',
#         context={'form': form}
#     )


class GroupUpdateView(LoginRequiredMixin, UpdateView):
    model = Group
    form_class = GroupUpdateForm
    success_url = reverse_lazy('groups:list')
    template_name = 'groups/update.html'


# def update_group(request, pk):
#
#     group = get_object_or_404(Group, id=pk)
#
#     if request.method == 'GET':
#
#         form = GroupUpdateForm(instance=group)
#
#     elif request.method == 'POST':
#
#         form = GroupUpdateForm(instance=group, data=request.POST)
#
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('groups:list'))
#
#     return render(
#         request=request,
#         template_name='groups/update.html',
#         context={'form': form}
#     )


class GroupDeleteView(LoginRequiredMixin, DeleteView):
    model = Group
    form_class = GroupDeleteForm
    success_url = reverse_lazy('groups:list')
    template_name = 'groups/delete.html'

# def delete_group(request, pk):
#
#     groups = get_object_or_404(Group, id=pk)
#
#     if request.method == 'POST':
#         groups.delete()
#         return HttpResponseRedirect(reverse('groups:list'))
#
#     return render(
#         request=request,
#         template_name='groups/delete.html',
#         context={'groups': groups}
#     )

groups/templates/groups/create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Create student
{% endblock %}

{% block header %}
    Creating student
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{form | crispy}}
        <input class="btn btn-success mb-3 mt-3" type="submit" value="Create">
        <a class="btn btn-primary" href="{% url 'groups:list' %}">Cancel</a>
    </form>
{% endblock %}

groups/templates/groups/delete.html
{% extends 'base.html' %}

{% block title %}
    Delete student
{% endblock %}

{% block header %}
   Removing student
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Are you sure to delete {{object.first_name}} {{object.last_name}} ?</p>
        <input class="btn btn-primary" type="submit" value="Agree">
        <a class="btn btn-danger" href="{% url 'groups:list' %}">Cancel</a>
    </form>
{% endblock %}

groups/templates/groups/list.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Group's list
{% endblock %}

{% block header %}
    List of group
{% endblock %}

{% block content %}
<div class="collapse" id="collapseExample">
    <form method="get">
        {% csrf_token %}
        {{ object_filter.form | crispy }}
        <input class="btn btn-success mb-3 mt-3" type="submit" value="Search">
    </form>
</div>
    <p><strong>Student's count {{ object_list.count }}</strong></p>

    <table class="table table-sm">
        <tr>
            <th>N</th>
            <th>First name</th>
            <th>Last name</th>
            <th>City</th>
            <th>Phone number</th>
            <th>Birthday</th>
            <th>Email</th>
            <th>Teachers</th>
            <th><i class="bi bi-pencil"></i></th>
            <th><i class="bi bi-trash-fill"></i></th>
        </tr>
        {% for student in object_list %}
        <tr>
            <td>{{page_obj.start_index|add:forloop.counter0}}</td>
            <td>{{student.first_name}}</td>
            <td>{{student.last_name}}</td>
            <td>{{student.city}}</td>
            <td>{{student.phone_number}}</td>
            <td>{{student.birthday}}</td>
            <td>{{student.email}}</td>
            <td>{% if student.teacher %}{{ student.teacher }}{% endif %}</td>
            <td> <a href = "{% url 'groups:update' student.id %}">EDIT</a> </td>
            <td> <a href = "{% url 'groups:delete' student.id %}">DELETE</a> </td>
        </tr>
        {% endfor %}
    </table>>
    {% if is_paginated %}
        {% include 'includes/paginator.html' %}
    {% endif %}
{% endblock %}

groups/templates/groups/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
   Update student
{% endblock %}

{% block header %}
   Updating student
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{form | crispy}}
        <input class="btn btn-primary mt-3" type="submit" value="Update">
        <a class="btn btn-primary mt-3" href="{% url 'groups:list' %}">Cancel</a>
    </form>
{% endblock %}