lms/urls.py
from core.views import index

import debug_toolbar

from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('groups/', include('groups.urls')),
    path('teachers/', include('teachers.urls')),
    path('courses/', include('courses.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teachers/urls.py
from django.urls import path
# from teachers.views import create_teacher, delete_teacher, get_teachers, update_teacher

from .views import TeacherCreateView, TeacherDeleteView, TeacherListView, TeacherUpdateView
app_name = 'teachers'

urlpatterns = [
    path('', TeacherListView. as_view(), name='list'),
    path('create', TeacherCreateView.as_view(), name='create'),
    path('update/<int:pk>', TeacherUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', TeacherDeleteView.as_view(), name='delete'),
]

teachers/models.py
from core.models import Person

from django.db import models

from faker import Faker


class Teacher(Person):
    phone_number = models.CharField(max_length=60, unique=True, blank=True, null=True)

    def __str__(self):
        return f'{self.first_name}, {self.last_name}'

    @staticmethod
    def generate_teachers(*args):
        faker = Faker()
        for _ in range(*args):
            st = Teacher(
                first_name=faker.first_name(),
                last_name=faker.last_name(),
                phone_number=faker.phone_number(),
                city=faker.city(),
                email=faker.email(),
            )
            st.save()

teachers/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm

import django_filters # noqa

from teachers.models import Teacher


class TeacherBaseForm(ModelForm):
    class Meta:
        model = Teacher
        fields = ['first_name', 'last_name', 'phone_number', 'city']

    @staticmethod
    def normalize_phone_number(value):
        return ''.join(c for c in value if c.isdigit() or c == '+')

    def clean_phone_number(self):
        phone_number = self.cleaned_data['phone_number']
        if Teacher.objects.filter(phone_number=phone_number).exclude(id=self.instance.id).exists():
            raise ValidationError("Already exist")
        result = self.normalize_phone_number(phone_number)
        return result


class TeacherCreateForm(TeacherBaseForm):
    pass


class TeacherUpdateForm(TeacherBaseForm):
    pass


class TeacherDeleteForm(TeacherBaseForm):
    pass

class TeacherFilter(django_filters.FilterSet):
    class Meta:
        model = Teacher
        fields = {
            'first_name': ['exact', 'icontains'],
            'last_name': ['exact', 'startswith'],
        }

teachers/views.py
# from django.http import HttpResponseRedirect
# from django.shortcuts import get_object_or_404, render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy  # noqa
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from teachers.forms import TeacherBaseForm, TeacherCreateForm, TeacherDeleteForm, TeacherUpdateForm, TeacherFilter
from teachers.models import Teacher

from copy import copy
# from webargs import fields
# from webargs.djangoparser import use_args


# @use_args({
#     "first_name": fields.Str(
#         required=False
#         ),
#     "last_name": fields.Str(
#         required=False
#         ),
#     "phone_number": fields.Str(
#         required=False
#         ),
#     "city": fields.Str(
#         required=False
#         )},
#     location="query"
#         )
# def get_teachers(request, args):
#     teachers = Teacher.objects.all()
#     # for param_name, param_values in args.items():
#     #     if param_values:
#     #         teachers = teachers.filter(**{param_name: param_values})
#
#     obj_filter = TeacherFilter(data=request.GET, queryset=teachers)
#
#     return render(
#         request=request,
#         template_name='teachers/list.html',
#         context={
#             'teachers': teachers,
#             'obj_filter': obj_filter,
#         }
#     )
#
# def create_teacher(request):
#
#     if request.method == 'GET':
#
#         form = TeacherCreateForm()
#
#     if request.method == 'POST':
#
#         form = TeacherCreateForm(request.POST)
#
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('teachers:list'))
#
#     return render(
#         request=request,
#         template_name='teachers/create.html',
#         context={'form': form}
#     )
#
# def update_teacher(request, pk):
#
#     teachers = get_object_or_404(Teacher, id=pk)
#
#     if request.method == 'GET':
#
#         form = TeacherUpdateForm(instance=teachers)
#
#     elif request.method == 'POST':
#
#         form = TeacherUpdateForm(instance=teachers, data=request.POST)
#
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('teachers:list'))
#
#     return render(
#         request=request,
#         template_name='teachers/update.html',
#         context={'form': form}
#     )
#
#
# def delete_teacher(request, pk):
#
#     teachers = get_object_or_404(Teacher, id=pk)
#
#     if request.method == 'POST':
#         teachers.delete()
#         return HttpResponseRedirect(reverse('teachers:list'))
#
#     return render(
#         request=request,
#         template_name='teachers/delete.html',
#         context={'teachers': teachers}
#     )


class TeacherListView(LoginRequiredMixin, ListView):
    paginate_by = 15
    model = Teacher
    form_class = TeacherBaseForm
    success_url = reverse_lazy('teachers:list')
    template_name = 'teachers/list.html'

    def get_filter(self):
        return TeacherFilter(
            data=self.request.GET,
            queryset=self.model.objects.all().order_by('id')
        )

    def get_queryset(self):
        return self.get_filter().qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_filter'] = self.get_filter()
        params = self.request.GET
        if 'page' in params:
            params = copy(params)
            del params['page']
        context['get_params'] = params.urlencode()
        return context


class TeacherCreateView(LoginRequiredMixin, CreateView):
    model = Teacher
    form_class = TeacherCreateForm
    success_url = reverse_lazy('teachers:list')
    template_name = 'teachers/create.html'


class TeacherUpdateView(LoginRequiredMixin, UpdateView):
    model = Teacher
    form_class = TeacherUpdateForm
    success_url = reverse_lazy('teachers:list')
    template_name = 'teachers/update.html'


class TeacherDeleteView(LoginRequiredMixin, DeleteView):
    model = Teacher
    form_class = TeacherDeleteForm
    success_url = reverse_lazy('teachers:list')
    template_name = 'teachers/delete.html'

teachers/templates/teachers/create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Create teacher
{% endblock %}

{% block header %}
    Creating teacher
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form | crispy }}
        <input class="btn btn-success mb-3 mt-3" type="submit" value="Create">
        <a class="btn btn-primary" href="{% url 'teachers:list' %}">Cancel</a>
    </form>
{% endblock %}

teachers/templates/teachers/delete.html
{% extends 'base.html' %}

{% block title %}
    Delete teacher
{% endblock %}

{% block header %}
    Removing teacher
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Are you sure to delete {{object.first_name}} {{object.last_name}} ?</p>
        <input class="btn btn-primary" type="submit" value="Agree">
        <a class="btn btn-danger" href="{% url 'teachers:list' %}">Cancel</a>
    </form>
{% endblock %}

teachers/templates/teachers/list.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Teacher's list
{% endblock %}

{% block header %}
    List of teachers
{% endblock %}

{% block content %}
<div class="collapse" id="collapseExample">
<form method="get">
    {{ object_filter.form | crispy }}
    <input class="btn btn-success mb-3 mt-3" type="submit" value="Search">
    </form>
</div>
    <p><strong>Teacher's count {{ object_list.count }}</strong></p>

    <table class="table table-sm">
        <tr>
            <th>N</th>
            <th>First name</th>
            <th>Last name</th>
            <th>Phone number</th>
            <th>City</th>
            <th>Email</th>
            <th><i class="bi bi-pencil"></i></th>
            <th><i class="bi bi-trash-fill"></i></th>
        </tr>
        {% for teach in object_list %}
        <tr>
            <td>{{page_obj.start_index|add:forloop.counter0}}</td>
            <td>{{teach.first_name}}</td>
            <td>{{teach.last_name}}</td>
            <td>{{teach.phone_number}}</td>
            <td>{{teach.city}}</td>
            <td>{{teach.email}}</td>
<!--            <td>{%if teach.groups %}{{teach.groups}}{% endif %}</td>-->
            <td> <a href = "{% url 'teachers:update' teach.id %}">EDIT</a> </td>
            <td> <a href = "{% url 'teachers:delete' teach.id %}">DELETE</a> </td>
        </tr>
        {% endfor %}
    </table>>
    {% if is_paginated %}
        {% include 'includes/paginator.html' %}
    {% endif %}
{% endblock %}

teachers/templates/teachers/update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Update teacher
{% endblock %}

{% block header %}
    Updating teacher
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{form | crispy}}
        <input class="btn btn-primary mt-3" type="submit" value="Update">
        <a class="btn btn-primary mt-3" href="{% url 'teachers:list' %}">Cancel</a>
    </form>
{% endblock %}