accounts/urls.py
from django.urls import path

from .views import AccountRegistrationView, AccountLoginView, AccountLogoutView, AccountUpdateView

app_name = 'accounts'

urlpatterns = [
    path('registration/', AccountRegistrationView.as_view(), name='registration'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile_update/', AccountUpdateView.as_view(), name='profile_update'),

]

courses/urls.py
from courses.views import CourseCreateView, CourseDeleteView, CourseListView, CourseUpdateView

from django.urls import path

app_name = 'courses'

urlpatterns = [
    path('', CourseListView.as_view(), name='list'),
    path('create/', CourseCreateView.as_view(), name='create'),
    path('update/<int:pk>/', CourseUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', CourseDeleteView.as_view(), name='delete'),
]

groups/urls.py
from django.urls import path

from groups.views import GroupCreateView, GroupDeleteView, GroupListView,  GroupUpdateView

app_name = 'groups'

urlpatterns = [
    path('', GroupListView.as_view(), name='list'),
    path('create/', GroupCreateView.as_view(), name='create'),
    path('update/<int:pk>/', GroupUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', GroupDeleteView.as_view(), name='delete'),
]

lms/urls.py
from core.views import index

import debug_toolbar

from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('groups/', include('groups.urls')),
    path('teachers/', include('teachers.urls')),
    path('courses/', include('courses.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teachers/urls.py
from django.urls import path
# from teachers.views import create_teacher, delete_teacher, get_teachers, update_teacher

from .views import TeacherCreateView, TeacherDeleteView, TeacherListView, TeacherUpdateView
app_name = 'teachers'

urlpatterns = [
    path('', TeacherListView. as_view(), name='list'),
    path('create', TeacherCreateView.as_view(), name='create'),
    path('update/<int:pk>', TeacherUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', TeacherDeleteView.as_view(), name='delete'),
]

templates/includes/messages.html
{% if messages %}
    {% for message in messages %}
    <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
    {% endfor %}
{% endif %}

templates/includes/nav_bar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top navbar-expand-lg font-weight-bold">
  <div class="container">
    <a class="navbar-brand" href="{% url 'index' %}">LMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'teachers:list' %}">Teachers</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'groups:list' %}">Group</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Group's menu
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'groups:list' %}">Group's list</a></li>
            <li><a class="dropdown-item" href="{% url 'groups:create' %}">Add new student</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Teacher's menu
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'teachers:list' %}">Teacher's list</a></li>
            <li><a class="dropdown-item" href="{% url 'teachers:create' %}">Add new teacher</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Course's menu
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'courses:list' %}">Course's list</a></li>
            <li><a class="dropdown-item" href="{% url 'courses:create' %}">Add new course</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/about/" tabindex="-1" >About Us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/contacts/" tabindex="-1" >Contacts</a>
        </li>
      </ul>
      {% if user.is_authenticated %}
          <div><img class="rounded-circle p-1 m-1" widht="40" height="40" src="{{user.profile.avatar.url}}"></div>
           {% endif %}
      <ul class="navbar-nav d-flex">
         <li class="nav-item dropdown">
           <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown3" role="button" data-bs-toggle="dropdown" aria-expanded="false">
             Account
           </a>
           <ul class="dropdown-menu" aria-labelledby="navbarDropdown3">
           {% if user.is_authenticated %}
               <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Sign Out</a></li>
               <li><hr class="dropdown-divider"></li>
               <li><a class="dropdown-item" href="{% url 'accounts:profile_update' %}">Profile {{ user.username }}</a></li>
               <li><a class="dropdown-item" href="{% url 'password_change' %}">Change password</a></li>
           {% else %}
             <li><a class="dropdown-item" href="{% url 'accounts:login' %}">Sign In</a></li>
             <li><hr class="dropdown-divider"></li>
             <li><a class="dropdown-item" href="{% url 'accounts:registration' %}">Sign Up</a></li>
           {% endif %}
           </ul>
         </li>
       </ul>
      <form class="d-flex">
        <a class="btn btn-outline-success" data-bs-toggle="collapse" href="#collapseExample" role="button"
           aria-expanded="false" aria-controls="collapseExample">
            Search
        </a>
      </form>
    </div>
  </div>
</nav>

templates/includes/paginator.html
<nav aria-label="Page navigation example">
  <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1{% if get_params %}&{{ get_params }}{% endif %}">&laquo; First</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if get_params %}&{{ get_params }}{% endif %}">Previous</a></li>
      {% endif %}

      {% for page_num in page_obj.paginator.page_range %}
        {% if page_num == page_obj.number %}
            <li class="page-item active"><a class="page-link" href="?page={{ page_num }}{% if get_params %}&{{ get_params }}{% endif %}">{{ page_num }}</a></li>
        {% elif page_num > page_obj.number|add:-3 and page_num < page_obj.number|add:3 %}
            <li class="page-item"><a class="page-link" href="?page={{ page_num }}{% if get_params %}&{{ get_params }}{% endif %}">{{ page_num }}</a></li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}{% if get_params %}&{{ get_params }}{% endif %}">Next</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}{% if get_params %}&{{ get_params }}{% endif %}">Last &raquo;</a></li>
      {% endif %}
  </ul>
</nav>