courses/urls.py
from courses.views import CourseCreateView, CourseDeleteView, CourseListView, CourseUpdateView

from django.urls import path

app_name = 'courses'

urlpatterns = [
    path('', CourseListView.as_view(), name='list'),
    path('create/', CourseCreateView.as_view(), name='create'),
    path('update/<int:pk>/', CourseUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', CourseDeleteView.as_view(), name='delete'),
]

lms/urls.py
from core.views import index

import debug_toolbar

from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('groups/', include('groups.urls')),
    path('teachers/', include('teachers.urls')),
    path('courses/', include('courses.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/models.py
from django.db import models


class Course(models.Model):
    discipline = models.CharField(max_length=60, unique=True, blank=True, null=True)
    course = models.OneToOneField('groups.Group', on_delete=models.SET_NULL, null=True, related_name='number_course')

    def __str__(self):
        return f'{self.discipline}, {self.course}'

courses/forms.py
from courses.models import Course

from django.forms import ModelForm


class CourseBaseForm(ModelForm):
    class Meta:
        model = Course
        fields = '__all__'
        exclude = ['course']


class CourseCreateForm(CourseBaseForm):
    pass


class CourseUpdateForm(CourseBaseForm):
    pass


class CourseDeleteForm(CourseBaseForm):
    pass

courses/views.py
from courses.forms import CourseBaseForm, CourseCreateForm, CourseDeleteForm, CourseUpdateForm
from courses.models import Course
from django.http import HttpResponseRedirect # noqa
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, render # noqa
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from django.urls import reverse, reverse_lazy # noqa


class CourseListView(LoginRequiredMixin, ListView):
    model = Course
    form_class = CourseBaseForm
    success_url = reverse_lazy('courses:list')
    template_name = 'courses/list.html'

# def get_course(request):
#     course = Course.objects.all()
#
#     return render(
#         request=request,
#         template_name='courses/list.html',
#         context={'course': course}
#     )


class CourseCreateView(LoginRequiredMixin, CreateView):
    model = Course
    form_class = CourseCreateForm
    success_url = reverse_lazy('courses:list')
    template_name = 'courses/create.html'

# def create_course(request):
#
#     if request.method == 'GET':
#
#         form = CourseCreateForm()
#
#     elif request.method == 'POST':
#
#         form = CourseCreateForm(request.POST)
#
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('courses:list'))
#
#     return render(
#         request=request,
#         template_name='courses/create.html',
#         context={'form': form}
#     )


class CourseUpdateView(LoginRequiredMixin, UpdateView):
    model = Course
    form_class = CourseUpdateForm
    success_url = reverse_lazy('courses:list')
    template_name = 'courses/update.html'

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['course'] = self.get_object().form
# def update_course(request, pk):
#
#     course = get_object_or_404(Course, id=pk)
#
#     if request.method == 'GET':
#
#         form = CourseUpdateForm(instance=course)
#
#     elif request.method == 'POST':
#
#         form = CourseUpdateForm(instance=course, data=request.POST)
#
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('courses:list'))
#
#     return render(
#         request=request,
#         template_name='courses/update.html',
#         context={'form': form}
#     )


class CourseDeleteView(LoginRequiredMixin, DeleteView):
    model = Course
    form_class = CourseDeleteForm
    success_url = reverse_lazy('courses:list')
    template_name = 'courses/delete.html'

# def delete_course(request, pk):
#
#     course = get_object_or_404(Course, id=pk)
#
#     if request.method == 'POST':
#         course.delete()
#         return HttpResponseRedirect(reverse('courses:list'))
#
#     return render(
#         request=request,
#         template_name='courses/delete.html',
#         context={'course': course}
#     )

courses/templates/courses/create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Create course
{% endblock %}

{% block header %}
    Creating course
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{form | crispy}}
        <input class="btn btn-success mb-3 mt-3" type="submit" value="Create">
        <a class="btn btn-primary" href="{% url 'courses:list' %}">Cancel</a>
    </form>
{% endblock %}

courses/templates/courses/delete.html
{% extends 'base.html' %}

{% block title %}
    Delete course
{% endblock %}

{% block header %}
   Removing course
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Are you sure to delete {{course.discipline}} ?</p>
        <input class="btn btn-primary" type="submit" value="Agree">
        <a class="btn btn-danger" href="{% url 'courses:list' %}">Cancel</a>
    </form>
{% endblock %}

courses/templates/courses/list.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Course's list
{% endblock %}

{% block header %}
    List of course
{% endblock %}

{% block content %}
<div class="collapse" id="collapseExample">
<form method="get">
        {% csrf_token %}
        {{ object_list.form | crispy }}
        <input class="btn btn-success mb-3 mt-3" type="submit" value="Search">
    </form>
</div>
    <p><strong>Course's count {{ object_list.count }}</strong></p>

    <table class="table table-sm">
        <tr>
            <th>N</th>
            <th>Discipline</th>
            <th><i class="bi bi-pencil"></i></th>
            <th><i class="bi bi-trash-fill"></i></th>
        </tr>
        {% for args in object_list %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td>{{args.discipline}}</td>
            <!--            <td>{%if teach.groups %}{{teach.groups}}{% endif %}</td>-->
            <td> <a href = "{% url 'courses:update' args.id %}">EDIT</a> </td>
            <td> <a href = "{% url 'courses:delete' args.id %}">DELETE</a> </td>
        </tr>
        {% endfor %}
    </table>>
{% endblock %}

courses/templates/courses/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
   Update student
{% endblock %}

{% block header %}
   Updating student
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form | crispy}}
        <input class="btn btn-primary mt-3" type="submit" value="Update">
        <a class="btn btn-primary mt-3" href="{% url 'courses:list' %}">Cancel</a>
    </form>
{% endblock %}